### ISSUE TITLE
socks5代理不能正常访问

### ISSUE THREAD

**Issue by Mybrc91** [avwo/whistle#1034]
socks5代理不能正常访问，帮忙看下什么问题，谢谢。

whistle配置如下：
`* socks://192.168.1.151:20080`
配置后访问xxx.com不能访问，返回
```
Error: host is unreachable
    at Parser._onData (/usr/local/lib/node_modules/whistle/node_modules/sockx/lib/client.parser.js:121:17)
    at Parser.__onData (/usr/local/lib/node_modules/whistle/node_modules/sockx/lib/client.parser.js:33:10)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
使用SwitchyOmega配置如下，可以正常访问
<img width="842" alt="image" src="https://github.com/avwo/whistle/assets/2195213/4b1db5e4-2f78-4d01-af2c-3e2d9f759cd0">

**Comment by avwo** [comment]
看起来像是dns问题，换个域名看看

**Comment by Mybrc91** [comment]
> 换个域名看看

dns 问题，换域名可以了，谢谢
