### ISSUE TITLE
开启代理后访问任何地址都提示连接超时

### ISSUE THREAD

**Issue by gengfanbin** [avwo/whistle#1063]
如题，win11系统中开启代理后任何连接都超时

错误信息
From: whistle@2.9.68
Node: v20.4.0
Host: DESKTOP-AHVOSQ8
Date: 2024/4/11 16:13:51
Error: socket connect timeout
    at retry (C:\Users\seable\AppData\Roaming\nvm\v20.4.0\node_modules\whistle\lib\inspectors\res.js:546:34)
    at Timeout._onTimeout (C:\Users\seable\AppData\Roaming\nvm\v20.4.0\node_modules\whistle\lib\inspectors\res.js:668:31)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

重新安装whistle依然这样。尝试了很多办法，重装CA，重启代理，手动配置代理，都无法解决。。帮忙看一下问题呗

**Comment by avwo** [comment]
这个跟你本机网络有关，用 chrome 抓包看下不走代理你们的请求是怎么走的

**Comment by gengfanbin** [comment]
它甚至有个奇怪的现象，就是在开启代理的很短时间内，估计1~2秒内，我可以访问到写在w2 rules中的文件。然后就断网了。

**Comment by gengfanbin** [comment]
换成手机热点后，无法复现这个问题了，但是我还是没明白为什么在本地网络中会出现这个问题。我应该从哪里开始排查？毕竟我不能一直跑热点流量

**Comment by avwo** [comment]
不配系统代理试试

**Comment by gengfanbin** [comment]
不配置系统代理的时候 rule 设置的规则好像不生效，我无法访问到rule规则里的文件

**Comment by JackZong** [comment]
有个同样的问题：
`
https://abc.com/api/ https://abc.com/api/
https://abc.com/ http://localhost:5174/
wss://abc.com/ ws://localhost:5174/
`
所有abc.com的请求都成功代理到了whistle，localhost:5174也成功响应，但是不知道为啥/api/xxx的请求偶尔可以通几次，大部分时间都会报 Error: socket connect timeout。

帮忙看一下～

**Comment by avwo** [comment]
> 一样，刚更新的最新版。
> 
> ![Image](https://github.com/user-attachments/assets/1c67323e-7c4f-4244-ab1c-ce683f4a1757)

自己还是公司的电脑

**Comment by MarvinXu** [comment]
> > 一样，刚更新的最新版。
> > ![Image](https://github.com/user-attachments/assets/1c67323e-7c4f-4244-ab1c-ce683f4a1757)
> 
> 自己还是公司的电脑

家里的，联通网，刚安装什么都没配置，就装了https证书。不开代理正常上网

**Comment by avwo** [comment]
打开右上角 `Online` 看下网络设置

<img width="706" alt="Image" src="https://github.com/user-attachments/assets/1d741dca-d57e-47e7-a7e8-28acea73837f" />

**Comment by MarvinXu** [comment]
![Image](https://github.com/user-attachments/assets/2201614a-70c0-47d5-909b-e79abb8a2a88)

**Comment by avwo** [comment]
切到 IPv4 first 试试

<img width="339" alt="Image" src="https://github.com/user-attachments/assets/6a09f873-f326-4498-b6c4-46f0df93dda5" />

**Comment by MarvinXu** [comment]
emm 现在好了。也没动什么，昨晚上电脑休眠了，刚打开就可以了

**Comment by MarvinXu** [comment]
![Image](https://github.com/user-attachments/assets/e7c0899f-2c91-400e-9f87-109486e15eec)

确实现在是ipv4地址，不过我没改配置
