### ISSUE TITLE
w2 start 在node v9.0.3 出错

### ISSUE THREAD

**Issue by beidan** [avwo/whistle#108]
错误信息如下：
_tls_common.js:59
    throw new errors.TypeError(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "cert" argument must be one of type string, Buffer, TypedArray, or DataView
    at validateKeyCert (_tls_common.js:59:11)
    at createSecureContext (_tls_common.js:118:7)
    at createRootCA (/usr/local/lib/node_modules/whistle/lib/https/ca.js:133:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/whistle/lib/https/ca.js:228:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)

**Comment by avwo** [comment]
Node 9的一些接口没向下兼容，更新下whistle就可以：https://avwo.github.io/whistle/update.html
