### ISSUE TITLE
抓包过程中, 如果碰到上传文件的post, 点开request raw,text 的时候会非常卡

### ISSUE THREAD

**Issue by shoaly** [avwo/whistle#110]
经过观察, 卡顿很可能是因为打印出了文件的二进制, 其实那部分代码本来也是乱码, 
1 能否直接隐藏掉 ?
2 或者显示一个额外的链接, 点击之后可以直接下载对应的二进制文件

**Comment by avwo** [comment]
鼠标hover到右上角的 `ViewAll`，可以看到下载按钮，或者直接点击 `ViewAll` 可以查看所有内容，现在最多显示64k，超过64k要打开 `ViewAll`，下个版本把这值减小到16k。

**Comment by shoaly** [comment]
感谢回复, 在我尝试download的时候 返回异常了. 
其实还可以考虑把文档说明也开源到github上.... 也许使用过的朋友会一起来完善文档, 目前发现w2做得不错, 叹息说明文档还不够丰富啊

Error: request entity too large
   at makeError (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\raw-body\index.js:184:15)
   at module.exports (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\raw-body\index.js:40:15)
   at read (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\body-parser\lib\read.js:64:3)
   at urlencodedParser (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\body-parser\lib\types\urlencoded.js:104:5)
   at Layer.handle [as handle_request] (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\express\lib\router\index.js:302:13)
   at D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\express\lib\router\index.js:321:12)
   at next (D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\node_modules\express\lib\router\index.js:261:10)
   at D:\Users\shoaly\AppData\Roaming\npm\node_modules\whistle\biz\webui\lib\index.js:213:5

**Comment by shoaly** [comment]
版本是最新的

**Comment by avwo** [comment]
文档确实做得不好，我正在把整个文挡重写，等把文档结构和基本内容及示例整好再发出来让大家一起帮忙完善。
你这个错误是怎么产生的，怎么重现？

**Comment by shoaly** [comment]
我这里次次都能重现... 是一张图片, 用不用发送文件给你试试....
除了文件以外, 本身这个包还是通过一个ocx以http post的方式上传的, 如果是ocx那边可能还没法给你了...步凑就麻烦了

*---------------------------------------------------------------------------------*

*Xuli Xiao 肖旭立*Mobile: 18602309133 | QQ: 18295742
Email: shoalyxiao@gmail.com
重庆和信慧科技有限公司 | 重庆市栖霞路金茂时代12栋1012
九天友邦文化传媒有限责任公司 | 北京市朝阳区西坝河东里101-2
Website: www.hexinhui.cn

2018-01-13 10:07 GMT+08:00 avenwu <notifications@github.com>:

**Comment by avwo** [comment]
你要把这个表单到哪，有可能你配错了，是不是直接用http请求了 `127.0.0.1:8899` ，如果是这样请求会直接发送到whistle的内部的UI服务器，该内部服务器只给UI用的，且最多支持1m大小的上传表单

**Comment by shoaly** [comment]
[whistle_20180113102708789.txt](https://github.com/avwo/whistle/files/1627976/whistle_20180113102708789.txt)

**Comment by avwo** [comment]
你导出的这个请求没看出什么问题。
上面提的界面卡顿问题已经做了优化，重新安装下whistle试试：
```
npm i -g whistle
w2 restart
```

**Comment by shoaly** [comment]
好的, 我更新试试看
