### ISSUE TITLE
安装后启动报错 

### ISSUE THREAD

**Issue by 18301294837** [avwo/whistle#1146]
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received type number (443)

node 安装版本 ：18.20.4  

详细报错 ： 

From: whistle@2.9.83
Node: v18.20.4
Host: V_TIMISU-PC7
Date: 2024/9/4 17:35:36
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received type number (443)
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:167:9)
    at Object.join (C:\Program Files\nodejs\node_modules\whistle\lib\util\index.js:2072:22)
    at C:\Program Files\nodejs\node_modules\whistle\lib\inspectors\res.js:395:50
    at C:\Program Files\nodejs\node_modules\whistle\lib\rules\dns.js:183:43
    at lookupDNS (C:\Program Files\nodejs\node_modules\whistle\lib\rules\dns.js:65:12)
    at lookup (C:\Program Files\nodejs\node_modules\whistle\lib\rules\dns.js:182:3)
    at proto.lookupHost (C:\Program Files\nodejs\node_modules\whistle\lib\rules\rules.js:2015:3)
    at proto.resolveHost (C:\Program Files\nodejs\node_modules\whistle\lib\rules\rules.js:2009:8)

Reload this page

**Comment by avwo** [comment]
`v2.9.83` 版本有个方法拼错了，重新安装下 Whistle
