### ISSUE TITLE
whistle@1.9.6在node@9.11.1环境中无法使用

### ISSUE THREAD

**Issue by markqin** [avwo/whistle#148]
_tls_common.js:59
    throw new errors.TypeError(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "cert" argument must be one of type string, Buffer, TypedArray, or DataView
    at validateKeyCert (_tls_common.js:59:11)
    at createSecureContext (_tls_common.js:118:7)
    at createRootCA (/usr/local/lib/node_modules/whistle/lib/https/ca.js:133:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/whistle/lib/https/ca.js:228:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)

**Comment by avwo** [comment]
我这边用windows试了 `Node 9.11.1` 没问题，你执行下`w2 -V` 看下版本号是不是`v1.9.6`的。
类似issue： https://github.com/avwo/whistle/issues/87

**Comment by markqin** [comment]
@avwo 是v1.5.6，我重新安装的，看来是`npm i -g whistle`没有拉到最新版本。node暂时降级到稳定版使用了，多谢

**Comment by avwo** [comment]
whistle在Node v9.11.1运行确实会有问题，可以看下这个issue：https://github.com/avwo/whistle/issues/150

尽量用whistle最新版本，当前最新版本为`v1.9.8`，你这种情况可能是升级Node后全局安装路径变更，但命令行还是找原来的路径，可以执行 `which w2` 把输出的对应路径命令行文件删掉试试。
