### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by helinjiang** [avwo/whistle#179]
运行 `w2` 的任何命令都会报如下错误，例如 `w2 -h` 的结果：

```
/usr/local/lib/node_modules/whistle/node_modules/graceful-fs/polyfills.js:11
    cwd = origCwd.call(process)
                  ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at process.cwd (/usr/local/lib/node_modules/whistle/node_modules/graceful-fs/polyfills.js:11:19)
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:390:17)
    at Function.Module._resolveFilename (module.js:460:31)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/whistle/bin/whistle.js:6:14)
    at Module._compile (module.js:570:32)
```

![image](https://user-images.githubusercontent.com/13464168/42216828-ba17b704-7ef5-11e8-807c-ac2f3ddec525.png)

![image](https://user-images.githubusercontent.com/13464168/42216755-7709e59a-7ef5-11e8-8973-657cd89e9ba8.png)

我本想全局重新安装的，没想到也是这个错误。我试过全局安装 pm2 是可以的，但是 whistle 就不行：
![image](https://user-images.githubusercontent.com/13464168/42217037-51df2482-7ef6-11e8-9ffc-12e43f37067b.png)

**Comment by avwo** [comment]
可能之前没安装好，删除目录重新安装试试：
````
rm -rf /usr/local/lib/node_modules/whistle
npm install -g whistle --registry=https://registry.npm.taobao.org
````
