### ISSUE TITLE
首次执行没问题，一刷新就是 Error - 500 错误

### ISSUE THREAD

**Issue by Mackerly** [avwo/whistle#219]
Error
Looks like something broke!

        
TypeError: Cannot read property 'indexOf' of undefined
    at exports.handleRequest (evalmachine.:8:33)
    at exports.handleRequest.next ()
    at onFulfilled (C:\Users\who\AppData\Roaming\npm\node_modules\whistle.script\node_modules\co\index.js:65:19)
    at 
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
===================
首次打开网页正常，也执行了符合if条件的操作，但是一刷新就是 Error - 500 错误。这是什么原因呢？
![image](https://user-images.githubusercontent.com/26422146/46209771-5af43d00-c361-11e8-9c1c-37c04d432967.png)

**Comment by avwo** [comment]
截图第三行代码，如果返回304时可能没有content-type，做下非空判断

**Comment by Mackerly** [comment]
> 截图第三行代码，如果返回304时可能没有content-type，做下非空判断

谢谢，是这个原因，已经解决了。
