### ISSUE TITLE
mac  启动失败

### ISSUE THREAD

**Issue by lyq4436** [avwo/whistle#230]
From: whistle@1.12.13
Node: v9.5.0
Date: 2018-10-23 16:17:02
TypeError: value.join is not a function
    at parseRules (/usr/local/lib/node_modules/whistle/lib/rules/util.js:117:19)
    at /usr/local/lib/node_modules/whistle/lib/rules/util.js:23:3
    at process._tickCallback (internal/process/next_tick.js:150:11)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

我试了下卸载重装还是不行，请大神帮忙看下

**Comment by avwo** [comment]
应该是你在 `Rules > Settings -> 勾选Back rules first` ，且配置的规则为空触发了该bug的，已经fix，重新安装下whistle。

**Comment by lyq4436** [comment]
已经可以了 谢谢
