### ISSUE TITLE
报了个错，ssl3的

### ISSUE THREAD

**Issue by yslion** [avwo/whistle#254]
大致结构是，浏览器代理到whistle ，whistle配置https-proxy规则，转发到squid ，squid转发到第三方https代理。

 把whistle环节摘除后，网络是通的，加入whistle，浏览器报这个错误。
求助 多谢

From: whistle@1.13.6
Node: v10.14.2
Date: 2019-1-11 13:07:02
Error: tunneling socket could not be established, cause=write EPROTO 16468:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:

    at ClientRequest.onError (C:\Users\root\AppData\Roaming\npm\node_modules\whistle\node_modules\_hagent@0.4.0@hagent\lib\agent.js:150:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at TLSSocket.Socket._destroy (net.js:617:3)
    at TLSSocket.destroy (internal/streams/destroy.js:32:8)

Reload this page

**Comment by avwo** [comment]
改成 `http-proxy` 试试

**Comment by yslion** [comment]
> 改成 `http-proxy` 试试

改了，比https的短了一些，但意思还是差不多。
一开始是浏览器-whistle- 第三方https的proxy ，不通，  加了ccproxy的二级代理
变成 浏览器-whistle- ccproxy-第三方https的proxy  不通 
现在把ccproxy换成了 squid 。 

From: whistle@1.13.6
Node: v10.14.2
Date: 2019-1-11 13:40:18
Error: write EPROTO 16468:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:

    at WriteWrap.afterWrite [as oncomplete] (net.js:792:14)


Reload this page

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/276
