### ISSUE TITLE
Mac 升级到最新版后报错

### ISSUE THREAD

**Issue by venshine** [avwo/whistle#287]
升级命令：
```sudo npm install -g whistle --registry=https://registry.npm.taobao.org```
<br/>
异常代码：
```
module.js:540
    throw err;
    ^

Error: Cannot find module '../lib/config'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/whistle/bin/whistle.js:5:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by avwo** [comment]
可能安装过程出错，卸载或删除后，重装安装

**Comment by venshine** [comment]
> 可能安装过程出错，卸载或删除后，重装安装

如何备份数据？数据存放在哪个目录或者有相关命令吗？

**Comment by avwo** [comment]
数据存在其它目录，更新或卸载、删除安装包都不会造成数据丢失

**Comment by venshine** [comment]
> 数据存在其它目录，更新或卸载、删除安装包都不会造成数据丢失

Thanks！

**Comment by jimmysuncpt** [comment]
Good!
