### ISSUE TITLE
mac whistle 长时间放置后挂掉了

### ISSUE THREAD

**Issue by Kinka** [avwo/whistle#37]
TypeError: Cannot read property 'on' of undefined
    at Object.fork (/usr/local/lib/node_modules/whistle/node_modules/pfork/lib/index.js:79:14)
    at loadPlugin (/usr/local/lib/node_modules/whistle/lib/plugins/index.js:214:5)
    at /usr/local/lib/node_modules/whistle/lib/plugins/index.js:323:5
    at Array.forEach (native)
    at loadPlugins (/usr/local/lib/node_modules/whistle/lib/plugins/index.js:319:11)
    at getRulesFromPlugins (/usr/local/lib/node_modules/whistle/lib/plugins/index.js:337:3)
    at getRulesMgr (/usr/local/lib/node_modules/whistle/lib/plugins/index.js:504:3)
    at EventEmitter.pluginMgr.getResRules (/usr/local/lib/node_modules/whistle/lib/plugins/index.js:515:3)
    at ServerResponse.res.response (/usr/local/lib/node_modules/whistle/lib/inspectors/res.js:365:15)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/whistle/lib/inspectors/res.js:332:25)

**Comment by avwo** [comment]
更新版本看看:
```
npm i -g whistle --registry=https://registry.npm.taobao.org
w2 restart
```
