### ISSUE TITLE
端口占用时，建议优化提示

### ISSUE THREAD

**Issue by shenlm203** [avwo/whistle#4]
目前启动whistle的时候， 如果端口被占用， 会直接抛出js错误。 建议优化提示

```
simon  sudo whistle start
Date: 2016-03-30 14:12:07.645
Error: listen EADDRINUSE :::8899
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1227:14)
    at listen (net.js:1263:10)
    at Server.listen (net.js:1359:5)
    at EventEmitter.app.listen (/usr/local/lib/node_modules/whistle/node_modules/express/lib/application.js:595:24)
    at proxy (/usr/local/lib/node_modules/whistle/lib/index.js:197:19)
    at init (/usr/local/lib/node_modules/whistle/index.js:3:25)
    at Command.<anonymous> (/usr/local/lib/node_modules/whistle/node_modules/starting/lib/bootstrap.js:10:4)
    at Command.listener (/usr/local/lib/node_modules/whistle/node_modules/starting/node_modules/commander/index.js:289:8)
```

**Comment by avwo** [comment]
很好的建议，[请更新whistle](https://github.com/avwo/whistle/wiki/%E6%9B%B4%E6%96%B0whistle)
