### ISSUE TITLE
docker部署，但是非127.0.0.1访问http的8899端口就报错

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#401]
```
From: whistle@1.10.3
Node: v8.9.3
Date: 2020-3-31 02:44:43
Error: connect EHOSTUNREACH 169.254.208.1:8899
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)


<a href="javascript:;" onclick="location.reload()">Reload page</a>

```

**Comment by aogg** [comment]
或者说如何增加http的8899可访问的ip，不要只有自动识别的ip，还可以指定特定的ip访问

**Comment by avwo** [comment]
加命令行参数-L ip

**Comment by aogg** [comment]
@avwo -l ip成功
小写
```bash
docker run -d --name whistle --restart=always -p 8899:8899 zlee/whistle -l 169.254.208.1
```
