### ISSUE TITLE
whistle@2.4.15 异常崩溃

### ISSUE THREAD

**Issue by xp-abc** [avwo/whistle#402]
**Bug description:**

program terminated abnormally

**Carsh log like:**

```text
[i] whistle@2.4.15 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://172.17.0.2:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. configure your device to use whistle as its HTTP and HTTPS proxy on IP:8899
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Press [Ctrl+C] to stop whistle...
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:319:13)
    at SendStream.send (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:501:17)
    at onstat (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:600:10)
    at FSReqCallback.oncomplete (fs.js:172:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:319:13)
    at SendStream.send (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:501:17)
    at onstat (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:600:10)
    at FSReqCallback.oncomplete (fs.js:172:5)
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:319:13)
    at SendStream.send (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:501:17)
    at onstat (/usr/local/lib/node_modules/whistle/node_modules/send/index.js:600:10)
    at FSReqCallback.oncomplete (fs.js:172:5)
```

**Steps to reproduce the issue:**

```bash
root@whistle:/root/docker/w2# cat Dockerfile
FROM node

RUN npm install -g whistle

ENTRYPOINT ["w2"]

root@whistle:/root/docker/w2# docker run --rm w2 run -p 8899 -n xp -w admin -P 8090
```

***Technical details:***
```bash
node -v
v13.12.0
```
```bash
docker -v
Docker version 18.06.1-ce, build e68fc7a
```
```bash
w2 --version
2.4.15
```

**Comment by avwo** [comment]
更新下 whistle 试试，不应该有这种错误，看下如何重现？

**Comment by xp-abc** [comment]
感谢回复，我更新至最新v2.4.17试试

重现可能有些麻烦，测试/开发团队均在使用，场景并非单一化

**Comment by avwo** [comment]
更新后还有类似问题么？按理来说即使出现这种异常，也不应该整个进程 carsh。

**Comment by avwo** [comment]
重新安装 whistle 并重启
