### ISSUE TITLE
更新到 2.5.0 后， 长轮训 20秒 ，提示超时 Error: socket connect timeout

### ISSUE THREAD

**Issue by caihuiji** [avwo/whistle#412]
From: whistle@2.5.2
Node: v10.16.0
Date: 2020-4-24 7:50:55 PM
Error: socket connect timeout
    at retry (D:\nvm\v10.16.0\node_modules\whistle\lib\inspectors\res.js:380:59)
    at Timeout._onTimeout (D:\nvm\v10.16.0\node_modules\whistle\lib\inspectors\res.js:472:25)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Reload this page

**Comment by caihuiji** [comment]
![image](https://user-images.githubusercontent.com/2292731/80209963-85090080-8665-11ea-99d2-ae78ee1d5d5e.png)


看了一下代码 是这个引起的， 但是2.4.17 也有这段代码 ，麻烦作者看看 @avwo

**Comment by avwo** [comment]
是个bug，timer没有清除，重新安装下 whistle 并重启。

**Comment by internalclass** [comment]
你好 我重新安装并重启还会报错 
![image](https://user-images.githubusercontent.com/3621805/80352335-5332ac80-88a6-11ea-985d-28b828a28787.png)

**Comment by avwo** [comment]
看下是不是自身网络问题，还有建议用最新版的node，性能更好且支持http2
