### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by ChrisCCheng** [avwo/whistle#478]
whistle代理出现下面的错误怎么解决呢？求教

From: whistle@2.5.16
Node: v10.16.3
Date: 2020-8-27 3:47:14 PM
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1095:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by avwo** [comment]
更新下whistle
