### ISSUE TITLE
做代理时异常退出

### ISSUE THREAD

**Issue by longkeyy** [avwo/whistle#48]
Error: connect EIO 124.243.193.116:443 - Local (0.0.0.0:0)
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at internalConnect (net.js:889:16)
    at lookupAndConnect (net.js:977:5)
    at TLSSocket.realConnect (net.js:945:5)
    at TLSSocket.Socket.connect (net.js:903:22)
    at TLSSocket.net.Socket.connect (/usr/local/lib/node_modules/whistle/index.js:21:22)
    at Object.exports.connect (_tls_wrap.js:1060:12)
    at Agent.createConnection (https.js:83:22)
    at Agent.createSocket (_http_agent.js:195:26)

**Comment by avwo** [comment]
Node版本和whistle的版本分别是多少？或者先把whistle更新到最新版本试试

**Comment by longkeyy** [comment]
Node v7.10.0 whistle 1.4.10

**Comment by avwo** [comment]
我这边暂时重现不了，你那边可以重现吗，可以的话加下QQ群：462558941

**Comment by avwo** [comment]
Node v7.10.0有bug会导致一些异常程序无法捕获，更新下Node版本即可：https://github.com/nodejs/node/issues/13077
