### ISSUE TITLE
代理错误：Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by iijin** [avwo/whistle#486]
#### 错误信息
```
From: whistle@2.5.20
Node: v12.18.3
Date: 2020-9-14 5:42:26 ├F10: PM┤
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:610:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1546:19)
    at Object.onceWrapper (events.js:421:28)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
#### 相似issue
https://github.com/avwo/whistle/issues/462
参照已close的issue https://github.com/avwo/whistle/issues/462 中的回复，更新了wishtle版本至2.5.20，并同时升级node版本至12.18.3，并未解决问题

#### 求助诉求
- 如问题需要升级node或者whistle版本解决，是否有指定的版本搭配
- 该问题是否有除了升级node或whistle版本外的解决方案，或者提供自行定位解决的思路也可以，如需补充错误信息可再完善

**Comment by avwo** [comment]
页面链接发我试下

**Comment by iijin** [comment]
是公司内的小网ip，外网无权限访问，有什么其他方式可以帮忙定位吗？

**Comment by avwo** [comment]
浏览器直接访问，把证书导出发我

**Comment by qld-cf** [comment]
可能是网络问题

**Comment by jiangdefu** [comment]
same problem

From: whistle@2.9.67
Node: v16.18.0
Date: 2024/4/7 16:22:14
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:705:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1594:19)
    at TLSSocket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
