### ISSUE TITLE
求助，w2 start启动后报错

### ISSUE THREAD

**Issue by TANCANJIE** [avwo/whistle#495]
w2 start启动后报错，whistle可以运行，但执行w2 stop后还在运行。

C:\Users\Administrator>w2 start
internal/fs/utils.js:230
    throw err;
    ^

Error: EPERM: operation not permitted, open 'C:\Users\Administrator\.startingAppData\error.C%3A%5CUsers%5CAdministrator%5CAppData%5CRoaming%5Cnpm%5Cnode_modules%5Cwhistle%5Cindex.js'
    at Object.openSync (fs.js:458:3)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:80:40
    at isRunning (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:27:10)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:64:5
    at isRunning (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:27:10)
    at start (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:59:3)
    at Timeout._onTimeout (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\node_modules\starting\lib\cli.js:133:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: 'C:\\Users\\Administrator\\.startingAppData\\error.C%3A%5CUsers%5CAdministrator%5CAppData%5CRoaming%5Cnpm%5Cnode_modules%5Cwhistle%5Cindex.js'
}

**Comment by avwo** [comment]
sudo w2 start
