### ISSUE TITLE
内网访问没问题，但采用公网地址就会报错

### ISSUE THREAD

**Issue by ZhangKejun** [avwo/whistle#499]
公网访问错误如下（自己用花生壳做了个内网穿透）：

From: whistle@2.5.22
Node: v12.18.3
Date: 10/9/2020, 4:08:45 PM
Error: socket hang up
    at connResetException (internal/errors.js:610:14)
    at Socket.socketOnEnd (_http_client.js:453:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Reload this page

**Comment by avwo** [comment]
内部网络问题，抓包看下ServerIP

**Comment by ZhangKejun** [comment]
> 内部网络问题，抓包看下ServerIP

就是不知道怎么处理这个错误，没有头绪；

**Comment by ZhangKejun** [comment]
> 内部网络问题，抓包看下ServerIP

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/15724876/95569105-b16bda00-0a57-11eb-9f20-260975baf256.png">

**Comment by avwo** [comment]
域名访问UI时，记得启动是加上 `-l hostname` 告诉whistle哪些域名用来访问UI。
