### ISSUE TITLE
使用的过程中突然出现了 operation not permitted 的报错

### ISSUE THREAD

**Issue by ClinkzM** [avwo/whistle#506]
这个问题该怎么解决呢？
是 win7 系统
` EPERM: operation not permitted, open 'C:\Users\Administrator\.WhistleAppData\.whistle\rules\.backup\13.v5.4%20-%20109.244.35.122%20-%20dev'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\lib\rules\storage.js:91:10
    at Array.forEach (<anonymous>)
    at new Storage (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\lib\rules\storage.js:70:31)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\whistle\lib\rules\util.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14) {
  errno: -4048,
  syscall: 'open',
  code: 'EPERM',
  path: 'C:\\Users\\Administrator\\.WhistleAppData\\.whistle\\rules\\.backup\\13.v5.4%20-%20109.244.35.122%20-%20dev'`

**Comment by avwo** [comment]
系统权限，网上搜下怎么解决

**Comment by dnsritch** [comment]
你解决这个问题了吗
公司电脑，无法使用管理员权限，
每次只能重启，很麻烦
