### ISSUE TITLE
文件行数太多（或许是）导致代理失败

### ISSUE THREAD

**Issue by aolose** [avwo/whistle#62]
转发一个有779行内容的js文件报错 本地访问显示正常
然后清空一般内容 又可以正常转发
然后不清空内容 批量去掉了js里的一些换行 合计344行 可以正常转发
还原文件到779行时候测试 报错又出现
#### 规则:
```
/.*xxxx\.com\:2018\/(.*)/ reqHeaders://{hder} proxy://localhost:54679/$1
```
#### 错误:
```
HTTP/1.1 502 Bad Gateway
content-type: text/html; charset=utf8
server: whistle

<pre>From: whistle@1.5.5
Node: v6.11.0
Date: 2017-8-22 13:45:22
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)</pre>
```

**Comment by avwo** [comment]
把请求的url发一下，可能是请求的响应头部有不规范的格式。
