### ISSUE TITLE
request frequently timeout

### ISSUE THREAD

**Issue by AlanWen2016** [avwo/whistle#695]
Whistle is not work stable for my Mac(iMac M1). Is anybody get same problem?

`
HTTP/1.1 502 Bad Gateway
content-type: text/html; charset=utf8
x-server: whistle

<pre>
From: whistle@2.8.5
Node: v12.21.0
Date: 2022-2-16 3:06:49 ├F10: PM┤
Error: socket connect timeout
    at retry (/opt/homebrew/lib/node_modules/whistle/lib/inspectors/res.js:431:59)
    at Timeout._onTimeout (/opt/homebrew/lib/node_modules/whistle/lib/inspectors/res.js:526:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

<a href="javascript:;" onclick="location.reload()">Reload this page</a>
</pre>
`

**Comment by avwo** [comment]
tcp 连接都无法建立，这种应该是你机器网络问题，换个 Wi-Fi 试试。
