### ISSUE TITLE
插件开发启用 --inspect 参数时，频繁出现 TypeError: Cannot read property 'AUTH' of undefined

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#727]
```
w2 run --inspect
Debugger listening on ws://127.0.0.1:9229/11716a43-9034-4655-a5b2-acb1a4b3dde8
For help, see: https://nodejs.org/en/docs/inspector
[i] whistle@2.9.12 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.1.103:8899/
       http://192.168.56.1:8899/
       http://192.168.196.109:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Press [Ctrl+C] to stop whistle...
Debugger attached.
From: whistle@2.9.12
Node: v14.16.0
Date: 2022/5/3 下午10:52:05
TypeError: Cannot read property 'AUTH' of undefined
    at Server.<anonymous> (D:\Users\AppData\Roaming\npm\node_modules\whistle\lib\plugins\load-plugin.js:1945:27)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
Waiting for the debugger to disconnect...

```

当这个报错出现时，就进入了等待调试器关闭，一旦关闭调试器，w2 进程就退出了！
如果不指定 --inspect 参数，不会出现这情况。
插件的环境是空项目用您提供的框架按选项单个的都选了Yes，多个的就全选，然后语言是 Typescript ，一行代码没修改就会出现这个情况。
Win10 环境

**Comment by avwo** [comment]
晚上发版本修复这个问题。

**Comment by avwo** [comment]
更新whistle 试试

**Comment by fjqingyou** [comment]
更新后没问题了。正常工作！
