### ISSUE TITLE
unable to start with node 9.0.0

### ISSUE THREAD

**Issue by iRalph** [avwo/whistle#87]
error messages:

_tls_common.js:59
    throw new errors.TypeError(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "cert" argument must be one of type string, Buffer, TypedArray, or DataView
    at validateKeyCert (_tls_common.js:59:11)
    at createSecureContext (_tls_common.js:108:7)
    at createRootCA (/usr/local/lib/node_modules/whistle/lib/https/ca.js:164:30)
    at Object.<anonymous> (/usr/local/lib/node_modules/whistle/lib/https/ca.js:259:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)

**Comment by avwo** [comment]
暂时先别用Node9，晚上发个版本fix这个问题

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)：
```
npm i -g whistle
w2 restart
```

**Comment by iRalph** [comment]
The problem has been solved. Thank you very much !
