### ISSUE TITLE
能支持ecc证书么

### ISSUE THREAD

**Issue by felithuang** [avwo/whistle#895]
使用ecc证书时报错：
Error: Could not convert private key from PEM; PEM header type is not "PRIVATE KEY" or "RSA PRIVATE KEY".
    at Object.pki.privateKeyFromPem (/usr/local/lib/node_modules/whistle/node_modules/node-forge/lib/pki.js:55:17)

**Comment by avwo** [comment]
怎么重现？

**Comment by felithuang** [comment]
我在 .WhistleAppData/ 下面建 certs 目录作为证书目录， 下面放上根证书：




目录查看如下 ：
```
.WhistleAppData/certs &gt; ls
root.crt root.key
```




其中这个根证书是用ecc算法的自签名根证书，证书信息如下：
```
.WhistleAppData/certs &gt; openssl x509 -text -noout -in root.crt
Certificate:
&nbsp; &nbsp; Data:
&nbsp; &nbsp; &nbsp; &nbsp; Version: 3 (0x2)
&nbsp; &nbsp; &nbsp; &nbsp; Serial Number: 100 (0x64)
&nbsp; &nbsp; Signature Algorithm: ecdsa-with-SHA256
&nbsp; &nbsp; &nbsp; &nbsp; Issuer: C=CN, ST=Guangdong, L=Shenzhen, O=february31st.com, CN=february31st.com
&nbsp; &nbsp; &nbsp; &nbsp; Validity
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Not Before: Jan&nbsp; 1 00:00:00 2000 GMT
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Not After : Jan&nbsp; 1 00:00:00 2100 GMT
&nbsp; &nbsp; &nbsp; &nbsp; Subject: C=CN, ST=Guangdong, L=Shenzhen, O=february31st.com, CN=february31st.com
&nbsp; &nbsp; &nbsp; &nbsp; Subject Public Key Info:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Public Key Algorithm: id-ecPublicKey
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Public-Key: (256 bit)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pub:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 04:db:7c:a9:ba:cb:3f:29:4a:1c:98:8e:10:ef:1b:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 4f:40:44:e4:17:a8:7c:8e:00:03:0b:3b:9d:4b:9b:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 7a:ff:ec:bc:3b:53:99:6d:df:07:67:cd:e5:93:05:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 9c:64:a1:ef:28:cf:cc:ce:3d:2e:a2:88:8f:18:98:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c1:ae:9b:47:45
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ASN1 OID: prime256v1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NIST CURVE: P-256
&nbsp; &nbsp; &nbsp; &nbsp; X509v3 extensions:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; X509v3 Subject Key Identifier:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; E1:82:21:33:25:6A:05:F3:D8:D9:F1:FC:1A:AB:0F:4D:11:DA:22:CD
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; X509v3 Authority Key Identifier:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; keyid:E1:82:21:33:25:6A:05:F3:D8:D9:F1:FC:1A:AB:0F:4D:11:DA:22:CD


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; X509v3 Basic Constraints:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; CA:TRUE
&nbsp; &nbsp; Signature Algorithm: ecdsa-with-SHA256
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;30:45:02:20:6e:2f:3d:bf:cb:0d:22:8f:37:24:5e:93:44:b1:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;75:f9:fb:b3:d2:8b:3b:16:69:51:4c:78:c3:c4:92:f5:ad:c5:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;02:21:00:8b:1f:f4:41:96:e0:9e:c7:77:ba:0d:b1:fa:98:cc:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;2c:ff:59:5c:f6:51:a3:2a:54:21:d4:61:16:7c:bd:51:ad
```




使用使用这个根证书启动whistle
```
.WhistleAppData/certs &gt; w2 start --certDir ./

[i] ***@***.*** started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
&nbsp; &nbsp; &nbsp; &nbsp;http://127.0.0.1:8899/
&nbsp; &nbsp; &nbsp; &nbsp;Note: If all the above URLs are unable to access, check the firewall settings
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with IP(127.0.0.1) &amp; PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
/usr/local/lib/node_modules/whistle/node_modules/node-forge/lib/pki.js:58
&nbsp; &nbsp; throw error;
&nbsp; &nbsp; ^


Error: Could not convert private key from PEM; PEM header type is not "PRIVATE KEY" or "RSA PRIVATE KEY".
&nbsp; &nbsp; at Object.pki.privateKeyFromPem (/usr/local/lib/node_modules/whistle/node_modules/node-forge/lib/pki.js:55:17)
&nbsp; &nbsp; at createRootCA (/usr/local/lib/node_modules/whistle/lib/https/ca.js:365:20)
&nbsp; &nbsp; at Object.<anonymous&gt; (/usr/local/lib/node_modules/whistle/lib/https/ca.js:518:1)
&nbsp; &nbsp; at Module._compile (node:internal/modules/cjs/loader:1191:14)
&nbsp; &nbsp; at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
&nbsp; &nbsp; at Module.load (node:internal/modules/cjs/loader:1069:32)
&nbsp; &nbsp; at Function.Module._load (node:internal/modules/cjs/loader:904:12)
&nbsp; &nbsp; at Module.require (node:internal/modules/cjs/loader:1093:19)
&nbsp; &nbsp; at require (node:internal/modules/cjs/helpers:108:18)
&nbsp; &nbsp; at Object.<anonymous&gt; (/usr/local/lib/node_modules/whistle/lib/https/index.js:19:10) {
&nbsp; headerType: 'EC PARAMETERS'
}

```






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "avwo/whistle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月24日(星期一) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [avwo/whistle] 能支持ecc证书么 (Issue #895)





 
怎么重现？

**Comment by avwo** [comment]
第三方库还不支持，估计要再等等：https://github.com/digitalbazaar/forge/pull/925
为什么一定要用 ecc 证书？
