### ISSUE TITLE
HTPPS Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by jason-ivy** [avwo/whistle#9]
Date: 2016-08-03 01:08:28.490
Error: connect ECONNREFUSED 218.30.108.181:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1062:14)

**Comment by avwo** [comment]
把请求url发我看下，我看看这边能不能重现

**Comment by avwo** [comment]
把Node更新到最新的LTS版本或当前最新版本试试看，低版本Node出现请求出错的概率大些，可能低版本Node的bug

**Comment by teal-front** [comment]
我今天在centos上也出现类似的错误了，whistle@1.9.2, node@6.9.5.猜想是不是服务器本身做了什么网络的限制了。
```config
From: whistle@1.9.2
Node: v6.9.5
Date: 3/19/2018, 9:36:33 AM
Error: connect ECONNREFUSED 123.207.44.185:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```
